spring:
  application:
    name: order-service
eureka:
  instance:
    appname: order-service

  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 9001
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        registerHealthIndicator: true
        slidingWindowSize: 100
  timelimiter:
    instances:
      inventory-service:
        timeoutDuration: 3s
      default:
        timeout-duration: 5s
        cancel-running-future: true



