spring:
  kafka:
    bootstrap-servers: localhost:9092,localhost:9093,localhost:9094
    consumer:
      enable-auto-commit: false
      group-id: bs-1
    producer:
      retries: 3
    listener:
      ack-mode: manual_immediate
server:
  port: 18080
mq:
  consumer: true