/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jni_thread_ThreadJNI */

#ifndef _Included_jni_thread_ThreadJNI
#define _Included_jni_thread_ThreadJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_thread_ThreadJNI
 * Method:    create
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jni_thread_ThreadJNI_create
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
