spring:
  datasource:
    url: jdbc:mysql://localhost:3306/biz?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: wonder@123
    driver-class-name: com.mysql.cj.jdbc.Driver
